### ISSUE TITLE
How to build overlap_tags.json

### ISSUE THREAD

**Issue by JonSmall** [cyber-meow/anime_screenshot_pipeline#39]
May I ask a question，how to build overlap_tags.json. Is there any way or repo I can search.
It must not be manual...

**Comment by gesen2egee** [comment]
https://danbooru.donmai.us/related_tag.json?query=1girl&category=general
Use this to fetch tags from the tagger. 
Then check which tags overlap; I recall the tolerance is set to 0.95.
