### ISSUE TITLE
ImportError: DLL load failed while importing libtorrent: The specified module could not be found. windows 10

### ISSUE THREAD

**Issue by 444butter** [cyber-meow/anime_screenshot_pipeline#50]
I am on windows 10, i have tried to download images with this tool but i keep on getting this error. i have installed requirements and tried installing libtorrent but failed. is there a way i can fix this

**Comment by cyber-meow** [comment]
This is a known issue as I explain on readme. For some reason libtorrent does not work on windows. As this only affects the anime downloading part (stage 0 for pipeline_type screenshots), you can just ignore it, download the anime yourself, and proceed with the remaining functionality.
